name: Auto Run Radar Facebook 1H

on:
  schedule:
    # Cấu hình CHẠY TỰ ĐỘNG 1 TIẾNG 1 LẦN (vào phút thứ 0 của mỗi giờ)
    - cron: '0 * * * *'
  # Cho phép bấm nút tự chạy thủ công để kiểm tra code
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pandas opencv-python ultralytics torch
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute Python script
      run: python main.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update data" && git push)
